# Generated by Django 5.2.3 on 2025-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[(1, 'Developer'), (2, 'Tester'), (2, 'Admin')], max_length=20),
        ),
    ]
