# Generated by Django 5.2.3 on 2025-07-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='account',
        ),
    ]
