# Generated by Django 5.2.3 on 2025-07-31 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0005_role_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
