# Generated by Django 5.2.3 on 2025-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0007_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Client'), (3, 'Developer')]),
        ),
    ]
