# Generated by Django 5.1.6 on 2025-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0010_alter_project_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='bug_attachments/'),
        ),
    ]
