# Generated by Django 5.1.6 on 2025-08-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0011_bug_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='desired_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
