# Generated by Django 5.1.6 on 2025-09-03 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0014_bug_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='project',
        ),
    ]
