# Generated by Django 5.1.6 on 2025-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0015_remove_bug_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
