# Generated by Django 5.1.6 on 2025-10-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0016_alter_bug_desired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='validity',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Valid', 'Valid'), ('Invalid', 'Invalid'), ('Duplicate', 'Duplicate')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Validated', 'Validated'), ('Invalid', 'Invalid'), ('Duplicate', 'Duplicate'), ('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='New', max_length=20),
        ),
    ]
