# Generated by Django 5.2.3 on 2025-10-05 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0017_delete_project_remove_bug_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
