# Generated by Django 5.2.3 on 2025-10-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0018_bug_created_at_bug_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(choices=[(1, 'Developer'), (2, 'Tester'), (3, 'Admin')]),
        ),
    ]
