# Generated by Django 5.2.3 on 2025-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker_app', '0019_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='admin_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
